### ISSUE TITLE
I have a routing error when the server is rendered asynchronously under SSR.

### ISSUE THREAD

**Issue by gsdukbh** [vuejs/vue-router-next#895]
### Version
4.0.0

### Reproduction link
[https://github.com/gsdukbh/vue3-ssr-demo](https://github.com/gsdukbh/vue3-ssr-demo)

### Steps to reproduce
Here is my configuration

### Universal entry file main.app.ts

```typescript
/* eslint-disable */
import {createApp, createSSRApp} from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";

const isSSR = typeof window === 'undefined'

export function buildApp() {
    const app = (isSSR ? createSSRApp(App) : createApp(App));
    app.use(router);
    app.use(store);
    return {app, router, store};
}

```

###  Client entry mian.ts

```typescript
/* eslint-disable */
import {buildApp} from './main.app';

const {app, router, store} = buildApp();

const storeInitialState =  (window as any).INITIAL_DATA;


if (storeInitialState) {
    store.replaceState(storeInitialState);
}

router.isReady()
    .then(() => {
        app.mount('#app');
    });

```

###  Server entrance  main.server.ts

```typescript
import { RouteLocationRaw } from 'vue-router';
import { buildApp } from './main.app';

export default (url: RouteLocationRaw) =>
  new Promise((resolve, reject) => {
    const { router, app, store } = buildApp();

  
    router.push(url);

    router
      .isReady()
      .then(() => {
        const matchedComponents = router.currentRoute.value.matched;
        // 
        if (!matchedComponents.length) {
          return reject(new Error('404'));
        }

        // Promise should be resolved to an application instance so that it can be rendered
        return resolve({ app, router, store });
      })
      .catch(() => reject);
  });

```

###  Server.js run in node

```typescript
/* eslint-disable */
/* @ts-ignore */
const serialize = require('serialize-javascript');
const path = require('path');
const express = require('express');
const fs = require('fs');
const {renderToString} = require('@vue/server-renderer');
const manifest = require('../dist/server/ssr-manifest.json');

// Create the express app.
const server = express();


// @ts-ignore
const appPath = path.join(__dirname, '../dist', 'server', manifest['app.js']);
const createApp = require(appPath).default;

const clientDistPath = '../dist/client';

// @ts-ignore
server.use('/img', express.static(path.join(__dirname, clientDistPath, 'img')));
// @ts-ignore
server.use('/js', express.static(path.join(__dirname, clientDistPath, 'js')));
// @ts-ignore
server.use('/css', express.static(path.join(__dirname, clientDistPath, 'css')));
// @ts-ignore
server.use('/favicon.ico', express.static(path.join(__dirname, clientDistPath, 'favicon.ico')));

// Handle all routes in our application
// @ts-ignore
server.get('*', async (req, res) => {
    const {app, store} = await createApp(req);

    let appContent = await renderToString(app);

    const renderState = `
    <script>
      window.INITIAL_DATA = ${serialize(store.state)}
    </script>`;

    // @ts-ignore
    fs.readFile(path.join(__dirname, clientDistPath, 'index.html'), (err, html) => {
            if (err) {
                throw err;
            }
            appContent = `<div id="app">${appContent}</div>`;

            html = html.toString().replace('<div id="app"></div>',
                `${renderState}${appContent}`);
            res.setHeader('Content-Type', 'text/html');
            res.send(html);
        });
});

const port = process.env.PORT || 8080;
server.listen(port, () => {
    console.log(`You can navigate to http://localhost:${port}`);
});

```

###  Routing file router/index.ts

```typescript
import {
  createMemoryHistory,
  createRouter,
  createWebHistory,
  RouteRecordRaw,
} from 'vue-router';
import Home from '../views/Home.vue';
// import About from '../views/About.vue';

const routes: Array<RouteRecordRaw> = [
  {
    path: '/',
    name: 'Home',
    component: Home,
    props: true,
  },
  {
    path: '/about',
    name: 'About',
    props: true,
    component: () => import(/* webpackChunkName: "about" */ '../views/About.vue'),
        // route level code-splitting
    // this generates a separate chunk (about.[hash].js) for this route
    // which is lazy-loaded when the route is visited.
// This method does not work correctly ,Server renderin
  },
];
const isServer = typeof window === 'undefined';
const history = isServer
  ? createMemoryHistory()
  : createWebHistory(process.env.BASE_URL);
const router = createRouter({
  history: history,
  routes,
});

export default router;

```
###  Error & problem

In server rendering mode，configuration code in router file `component: () => import(/* webpackChunkName: "about" */ '../views/About.vue')`。  An error is reported directly when accessing the `/ about` path.

```bash 
curl -L -O http://localhost:8080/about # Use this test.
```

Error message.

```txt
[Vue Router warn]: Path "/about" was passed with params but they will be ignored. Use a named route alongside params instead.
(node:11422) UnhandledPromiseRejectionWarning: Error: Cannot find module './js/about.0d8cd63d.js'
Require stack:
- /Users/lee/vue/hello-ssr/dist/server/js/app.b8fe1cc1.js
- /Users/lee/vue/hello-ssr/src/server.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Function.requireEnsure [as e] (/Users/leejiawei/vue/hello-ssr/dist/server/js/app.b8fe1cc1.js:46:25)
    at component (/Users/lee/vue/hello-ssr/dist/server/js/app.b8fe1cc1.js:964:32)
    at extractComponentsGuards (/Users/lee/vue/hello-ssr/node_modules/vue-router/dist/vue-router.cjs.js:1987:40)
    at /Users/lee/vue/hello-ssr/node_modules/vue-router/dist/vue-router.cjs.js:2623:22
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:11422) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)

```

### What is expected?
I want to be able to load routes asynchronously on the server.

### What is actually happening?
Unable to use, report an error directly.

**Comment by posva** [comment]
Please translate everything to English so I can take a look.

**Comment by gsdukbh** [comment]
> Please translate everything to English so I can take a look.

ok,My English is not that good. I beg your pardon.

**Comment by posva** [comment]
The error you see is unrelated to the router, it's something with the webpack config you have not correctly serving the js bundle containing your about page. You might want to take a look at https://github.com/frandiox/vite-ssr

**Comment by gsdukbh** [comment]
thank
